name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} 

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest"
          fail-build: false
          severity-cutoff: critical

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}